// Auto-generated by tools/02_hydrate_data.js — DO NOT EDIT MANUALLY

export interface HeroContent {
  title: string;
  subtitle: string;
  cta: string;
  cta_href: string;
}

export interface Capability {
  id: string;
  title: string;
  desc: string;
  icon: string;
}

export interface PipelineStep {
  step: string;
  label: string;
  desc: string;
}

export interface TrustedBrand {
  id: string;
  name: string;
}

export interface TechStackCategory {
  category: string;
  items: string[];
}

export interface FooterContent {
  cta_headline: string;
  cta: string;
  cta_href: string;
  contact: {
    email: string;
    location: string;
  };
  links: Array<{ label: string; href: string }>;
  copyright: string;
}

export interface SiteContent {
  hero: HeroContent;
  capabilities: Capability[];
  pipeline: PipelineStep[];
  trusted_by: TrustedBrand[];
  tech_stack: TechStackCategory[];
  footer: FooterContent;
}

export interface ContentRoot {
  content: SiteContent;
}
